Repository Financial-Times/origami-labels, pull requests merged in 2020-04, with the labels that each got.

#13 Add an OKR label
  README.md
  labels.js
Labels: proposal

#14 Add a current label
  README.md
  labels.js
Labels: proposal

#16 Add a pattern label
  labels.js
Labels: release:minor

#18 Add pending label
  labels.js
Labels: release:minor

#19 Document new labels `pattern` and `pending` in the README.
  README.md
Labels: release:patch
